version: 2.0

workflows:
  version: 2.0
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: python:3.6-alpine
    steps:
      - checkout
      - run:
          name: Test CoDeChan
          command: python test.py
