version: 2.0

workflows:
  version: 2
  test_dockerize_deploy:
    jobs:
      - test
      - dockerize:
          requires:
            - test
      - deploy-staging:
          requires:
            - dockerize
      - smoke-test:
          requires:
            - deploy-staging
      - deploy:
          requires:
            - smoke-test

jobs:
  test:
    docker:
      - image: python:3.6-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test CoDeChan
          command: python tests.py
  dockerize:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/codechan:$CIRCLE_SHA1 -t $DOCKER_USER/codechan:latest .
      - run: docker push $DOCKER_USER/codechan:$CIRCLE_SHA1
      - run: docker push $DOCKER_USER/codechan:latest
  deploy-staging:
    docker:
      - image: circleci/python:3.7
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:b2:8d:c5:3c:61:9e:44:93:37:a3:2b:cf:36:09:a2"
      - checkout
      - run:
          name: "Deploy to staging server"
          command: bash ./deploy.sh 34.77.143.146 $CIRCLE_SHA1
  smoke-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:b2:8d:c5:3c:61:9e:44:93:37:a3:2b:cf:36:09:a2"
      - checkout
      - run:
          name: "Run smoke test on staging"
          command: bash ./smoke-test.sh 34.77.143.146
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:b2:8d:c5:3c:61:9e:44:93:37:a3:2b:cf:36:09:a2"
      - checkout
      - run:
          name: "Deploy to production server"
          command: bash ./deploy.sh 35.233.86.108 $CIRCLE_SHA1
