version: 2.0

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: python:3.6-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test CoDeChan
          command: python tests.py
